// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/app" | "/app/booking-crm" | "/app/documents" | "/app/epk" | "/app/finance" | "/app/merch" | "/app/settings" | "/app/shows" | "/app/shows/[showId]" | "/app/tasks" | "/app/team" | "/app/tour-services" | "/app/tours" | "/auth/sign-in" | "/auth/sign-up" | "/onboarding"
type AppRouteHandlerRoutes = "/api/integrations/sumup/status" | "/api/routing/compute" | "/api/tours/import" | "/demo"
type PageRoutes = never
type LayoutRoutes = "/" | "/app"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/api/integrations/sumup/status": {}
  "/api/routing/compute": {}
  "/api/tours/import": {}
  "/app": {}
  "/app/booking-crm": {}
  "/app/documents": {}
  "/app/epk": {}
  "/app/finance": {}
  "/app/merch": {}
  "/app/settings": {}
  "/app/shows": {}
  "/app/shows/[showId]": { "showId": string; }
  "/app/tasks": {}
  "/app/team": {}
  "/app/tour-services": {}
  "/app/tours": {}
  "/auth/sign-in": {}
  "/auth/sign-up": {}
  "/demo": {}
  "/onboarding": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/app": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
